In [ ]:

import numpy as np
import pandas as pd

In [ ]:
# Question 1

In [2]:
# 1. Generate a 2D NumPy array of shape (5, 4) 
np.random.seed(0)
arr = np.random.randint(1, 51, size=(5, 4))
print("Original Array:\n", arr)

Original Array:
 [[45 48  1  4]
 [ 4 40 10 20]
 [22 37 24  7]
 [25 25 13  2]
 [39 40 24 47]]


In [3]:

# 2. Anti-Diagonal Elements(top-right to bottom-left)
anti_diagonal = [arr[i, -i-1] for i in range(min(arr.shape))]
print("\nAnti-diagonal elements:", anti_diagonal)


Anti-diagonal elements: [4, 10, 37, 25]


In [4]:
# 3. Maximum value in each row
row_max = np.max(arr, axis=1)
print("\nMaximum value in each row:", row_max)


Maximum value in each row: [48 40 37 25 47]


In [5]:
# 4. Elements that are <=mean
mean_value = np.mean(arr)
filtered_array = arr[arr <= mean_value]
print("\nElements <= mean (mean =", mean_value, "):", filtered_array)


Elements <= mean (mean = 23.85 ): [ 1  4  4 10 20 22  7 13  2]


In [6]:

# 5 Boundary traversal 
def numpy_boundary_traversal(matrix):
    if matrix.ndim != 2:
        raise ValueError("Input must be a 2D matrix.")
    
    rows, cols = matrix.shape
    boundary = []

    if rows == 1:
        boundary.extend(matrix[0, :])
    elif cols == 1:
        boundary.extend(matrix[:, 0])
    else:
        boundary.extend(matrix[0, :])
   
        boundary.extend(matrix[1:rows-1, -1])

        boundary.extend(matrix[-1, ::-1])
        
        boundary.extend(matrix[rows-2:0:-1, 0])

    return boundary

In [7]:

boundary = numpy_boundary_traversal(arr)
print("\nBoundary traversal in clockwise order:", boundary)


Boundary traversal in clockwise order: [45, 48, 1, 4, 20, 7, 2, 47, 24, 40, 39, 25, 22, 4]


In [8]:
# Question 2

In [9]:
import numpy as np

In [10]:
# 1. 1D array of 20 numbers
np.random.seed(1)  
arr = np.random.uniform(0, 10, 20)

# Round all elements to two decimal places
rounded_arr = np.round(arr, 2)
print("Rounded Array:\n", rounded_arr)

Rounded Array:
 [4.17 7.2  0.   3.02 1.47 0.92 1.86 3.46 3.97 5.39 4.19 6.85 2.04 8.78
 0.27 6.7  4.17 5.59 1.4  1.98]


In [11]:

# 2. Minimum , maximum and median
min_val = np.min(rounded_arr)
max_val = np.max(rounded_arr)
median_val = np.median(rounded_arr)

print("\nMinimum:", min_val)
print("Maximum:", max_val)
print("Median:", median_val)


Minimum: 0.0
Maximum: 8.78
Median: 3.715


In [12]:

# 3. < 5 with their squares
modified_arr = np.where(rounded_arr < 5, np.round(rounded_arr**2, 2), rounded_arr)
print("\nModified Array (elements < 5 squared):\n", modified_arr)


Modified Array (elements < 5 squared):
 [17.39  7.2   0.    9.12  2.16  0.85  3.46 11.97 15.76  5.39 17.56  6.85
  4.16  8.78  0.07  6.7  17.39  5.59  1.96  3.92]


In [13]:
# 4.  sorting of alternating smallest-largest pattern
def numpy_alternate_sort(array):
    sorted_array = np.sort(array)
    result = []
    i, j = 0, len(sorted_array) - 1
    while i <= j:
        result.append(sorted_array[i])
        if i != j:
            result.append(sorted_array[j])
        i += 1
        j -= 1
    return np.array(result)


alternate_sorted_arr = numpy_alternate_sort(rounded_arr)
print("\nAlternate Sorted Array (smallest, largest, ...):\n", alternate_sorted_arr)



Alternate Sorted Array (smallest, largest, ...):
 [0.   8.78 0.27 7.2  0.92 6.85 1.4  6.7  1.47 5.59 1.86 5.39 1.98 4.19
 2.04 4.17 3.02 4.17 3.46 3.97]


In [14]:
# Question 3


In [15]:
import pandas as pd

In [16]:
# 1. DF of 10 names with their subjects
np.random.seed(2)
names = ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ivan', 'Judy']
subjects = ['Math', 'Science', 'English', 'Math', 'Science', 'English', 'Math', 'Science', 'English', 'Math']
scores = np.random.randint(50, 101, size=10)

df = pd.DataFrame({
    'Name': names,
    'Subject': subjects,
    'Score': scores,
    'Grade': ''  
})

In [17]:
# 2. Grades based on the marks/scores
def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Score'].apply(assign_grade)

In [18]:
# 3. DF stored in descending
sorted_df = df.sort_values(by='Score', ascending=False)
print("Sorted DataFrame by Score:\n", sorted_df)

Sorted DataFrame by Score:
       Name  Subject  Score Grade
2  Charlie  English     95     A
5    Frank  English     93     A
0    Alice     Math     90     A
8     Ivan  English     90     A
4      Eva  Science     72     C
6    Grace     Math     68     D
1      Bob  Science     65     D
7    Helen  Science     61     D
3    David     Math     58     F
9     Judy     Math     57     F


In [19]:
# 4. Average score of subject
avg_scores = df.groupby('Subject')['Score'].mean()
print("\nAverage score per subject:\n", avg_scores)


Average score per subject:
 Subject
English    92.666667
Math       68.250000
Science    66.000000
Name: Score, dtype: float64


In [20]:
# 5. Records of Grade A and B
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]

filtered_df = pandas_filter_pass(df)
print("\nStudents with Grade A or B:\n", filtered_df)


Students with Grade A or B:
       Name  Subject  Score Grade
0    Alice     Math     90     A
2  Charlie  English     95     A
5    Frank  English     93     A
8     Ivan  English     90     A


In [21]:
# Question 4

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

positive_reviews = [
    "I loved the movie, it was fantastic!",
    "An excellent performance by the lead actor.",
    "A truly uplifting and heartwarming story.",
    "This film was a masterpiece, highly recommended.",
    "A brilliant screenplay and beautiful direction.",
    "Amazing visuals and great storytelling.",
    "Loved every moment of the film.",
    "One of the best movies I've seen this year.",
    "Outstanding! Will watch again.",
    "A delightful movie experience.",
] * 5  

negative_reviews = [
    "I hated the movie, it was terrible.",
    "The acting was awful and the story was boring.",
    "Complete waste of time.",
    "Poorly written and badly directed.",
    "The movie was dull and uninspired.",
    "I couldn't finish the movie, it was so bad.",
    "Terrible plot and weak characters.",
    "Nothing interesting happened.",
    "I regret watching this film.",
    "Boring and disappointing.",
] * 5  

reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * 50 + ['negative'] * 50

df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})


In [23]:
# 2.  CountVectorizer
vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

In [24]:
# 3. Traning-80% and testing-20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
# 4.  Multinomial Naive Bayes classifier
model = MultinomialNB()
model.fit(X_train, y_train)

# Predict and print accuracy
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", round(accuracy * 100, 2), "%")

Test Accuracy: 100.0 %


In [26]:
# 5 Prediction Function
def predict_review_sentiment(model, vectorizer, review):
    review_vector = vectorizer.transform([review])
    prediction = model.predict(review_vector)[0]
    return prediction


sample_review = "The movie was breathtaking and full of emotion!"
predicted_sentiment = predict_review_sentiment(model, vectorizer, sample_review)
print("\nSample Review Prediction:", predicted_sentiment)


Sample Review Prediction: negative


In [27]:
# Question 5


In [28]:
def predict_review_sentiment(model, vectorizer, review, show_prob=False):
    if not isinstance(review, str) or len(review.strip()) == 0:
        return "Invalid input: Review must be a non-empty string."

    review_vector = vectorizer.transform([review])
    prediction = model.predict(review_vector)[0]

    if show_prob:
        prob = model.predict_proba(review_vector)[0]
        return f"Sentiment: {prediction}, Probabilities: {dict(zip(model.classes_, prob.round(3)))}"
    
    return prediction


sample_review = "The movie was breathtaking and full of emotion!"
predicted_sentiment = predict_review_sentiment(model, vectorizer, sample_review, show_prob=True)
print("\nSample Review Prediction:", predicted_sentiment)



Sample Review Prediction: Sentiment: negative, Probabilities: {'negative': 0.678, 'positive': 0.322}
